#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" || exit ; pwd -P )"
export SCRIPTPATH

##
## Setup
##

## Chaotic AUR
sudo pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com
sudo pacman-key --lsign-key FBA220DFC880C036
sudo pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'

## Pacman
sudo cp pacman.conf /etc/pacman.conf
sudo pacman -S --noconfirm --needed archlinux-keyring
sudo pacman -Syuu --noconfirm
sudo pacman -S --noconfirm --needed archlinux-contrib

## Keyboard
sudo localectl set-keymap --no-convert us
sudo localectl --no-convert set-x11-keymap us pc104

## Time
sudo pacman -S --noconfirm --needed ntp
sudo systemctl enable ntpd.service
sudo systemctl start ntpd.service

## Network
sudo pacman -S --noconfirm --needed networkmanager network-manager-applet
sudo systemctl enable NetworkManager.service
sudo systemctl start NetworkManager.service

##
## Development
##

## Git
sudo pacman -S --noconfirm --needed git

## Rust
sudo pacman -S --noconfirm --needed rustup
rustup default stable

## Paru
mkdir -p $HOME/Git/paru
git clone https://aur.archlinux.org/paru.git $HOME/Git/paru
cd $HOME/Git/paru
makepkg -si --noconfirm
cd $HOME

## Java
paru -S --aur --noconfirm --needed jdk
archlinux-java set java-18-jdk

##
## System
##

## Microcode
sudo pacman -S --noconfirm --needed amd-ucode intel-ucode

## Xorg
sudo pacman -S --noconfirm --needed xorg-server xorg-apps xorg-drivers

## Sound
sudo pacman -S --noconfirm --needed pipewire gst-plugin-pipewire pipewire-alsa pipewire-jack wireplumber pipewire-pulse pavucontrol

## Bluetooth
sudo pacman -S --noconfirm --needed bluez bluez-libs bluez-tools bluez-utils blueman

## XDG
sudo pacman -S --noconfirm --needed xdg-utils archlinux-xdg-menu xdg-user-dirs xdg-desktop-portal xdg-desktop-portal-gtk xdg-desktop-portal-lxqt

## Voice
sudo pacman -S --noconfirm --needed espeak-ng espeakup
paru -S --aur --noconfirm --needed mbrola-voices-us2

## Printer
sudo pacman -S --noconfirm --needed cups hplip
paru -S --aur --noconfirm --needed hplip-plugin

##
## Theme
##

## Nordic-Theme/Nordzy
sudo pacman -S --noconfirm --needed python-pywal
wal --theme base16-nord
paru -S --aur --noconfirm --needed nordic-theme nordzy-cursors nordzy-icon-theme-git
gsettings set org.gnome.desktop.interface gtk-theme Nordic
gsettings set org.gnome.desktop.interface cursor-theme "Nordzy-cursors"
gsettings set org.gnome.desktop.interface icon-theme Nordzy-dark
mkdir ~/.themes && sudo cp -r /usr/share/themes/Nordic $HOME/.themes/Nordic
mkdir ~/.icons && sudo cp -r /usr/share/icons/Nordzy $HOME/.icons/Nordzy

## Fonts
sudo pacman -S --noconfirm --needed noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra 
paru -S --aur --noconfirm --needed nerd-fonts-noto
gsettings set org.gnome.desktop.interface font-name "Noto Sans Display 11"

##
## Containers / VMs
##

## Flatpak
sudo pacman -S --noconfirm --needed flatpak flatpak-xdg-utils

## Linux Containers
sudo pacman -S --noconfirm --needed lxc arch-install-scripts

## Virt Manager
sudo pacman -S --noconfirm --needed qemu virt-manager virt-viewer dnsmasq vde2 bridge-utils openbsd-netcat iptables-nft libguestfs
sudo systemctl enable libvirtd.service
sudo usermod -a -G libvirt $USER
newgrp libvirt
sudo systemctl start libvirtd.service
echo "options kvm-intel nested=1" | sudo tee /etc/modprobe.d/kvm-intel.conf
echo "options kvm-amd nested=1" | sudo tee /etc/modprobe.d/kvm-amd.conf

##
## Programs
##

## Shell
sudo pacman -S --noconfirm --needed fish
chsh -s /bin/fish $USER
sudo pacman -S --noconfirm --needed starship zoxide

## Desktop
paru -S --aur --noconfirm --needed leftwm leftwm-theme-git

## Session Manager
paru -S --aur --noconfirm --needed ly

## Utils
sudo pacman -S --noconfirm --needed ark bat bottom choose dog dua-cli dunst dust exa fd feh ffmpeg fzf git-delta gitui htmlq jq light mpv nfs-utils ntp pcmanfm-gtk3 polybar procs reflector ripgrep ripgrep-all rofi sd sxhkd tailscale tealdeer the_silver_searcher tig tokei ufw ufw-extras xdotool
paru -S --aur --noconfirm --needed jql nsxiv picom-ibhagwan-git pleaser sanctity xcp

## Music
sudo pacman -S --noconfirm --needed playerctl spotifyd
paru -S --noconfirm --needed spotify-tui sptlrx-bin

## Flatpak
flatpak install flathub --system --app --assumeyes --noninteractive --or-update org.audacityteam.Audacity com.discordapp.Discord org.mozilla.firefox org.gimp.GIMP com.obsproject.Studio org.onlyofffice.desktopeditors com.spotify.Client com.visualstudio.code
sudo flatpak override --filesystem=$HOME/.themes
sudo flatpak override --filesystem=$HOME/.icons
sudo flatpak override --env=GTK_THEME=Nordic

##
## Services
##

sudo systemctl enable ntpd.service
sudo systemctl enable cups.service
sudo systemctl enable ufw.service
sudo systemctl enable reflector.service
sudo systemctl enable preload.service
sudo systemctl enable ly.service
systemctl enable xdg-user-dirs-update.service --user

##
## Configuration Files
##

mkdir -p $HOME/.config
mkdir -p $HOME/.config/alacritty && cp $SCRIPTPATH/alacritty.yml $HOME/.config/alacritty/alacritty.yml
mkdir -p $HOME/.config/fish && cp $SCRIPTPATH/config.fish $HOME/.config/fish/config.fish
cp $SCRIPTPATH/starship.toml $HOME/.config/starship.toml
mkdir -p $HOME/.config/leftwm && cp $SCRIPTPATH/config.toml $HOME/.config/leftwm/config.toml
mkdir -p $HOME/.config/leftwm && cp $SCRIPTPATH/themes.toml $HOME/.config/leftwm/themes.toml
leftwm-theme update
leftwm-theme install "ColorSpace"
leftwm-theme apply "ColorSpace"
touch $HOME/leftwm/themes/ColorSpace/polybar/cache.txt

read -p "Would you like to reboot? (suggested) [Y/n] " yn
case $yn in
	[Yy]* ) reboot;;
	[Nn]* ) ;;
	"" ) reboot;;
	* )	echo "Please answer [y/n].";;
esac